### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by DanielRuf** [ghaiklor/node-print-message#140]
https://github.com/ghaiklor/node-print-message/compare/v2.1.0..dev

It seems there were a few changes regarding the dependencies.

**Comment by ghaiklor** [comment]
Why not? I will update the module, get rid of Babel maybe :)

**Comment by ghaiklor** [comment]
Updated, the latest version at the moment 3.0.1 - https://www.npmjs.com/package/print-message

Minor improvements in infra, replaced chalk with kleur...

**Comment by DanielRuf** [comment]
Awesome and great quality :1:

**Comment by DanielRuf** [comment]
Awesome and great quality :+1:
Many thanks.
