### ISSUE TITLE
Switch to kleur

### ISSUE THREAD

**Issue by DanielRuf** [ghaiklor/node-print-message#141]
Currently `chalk` has some issues when the script is invoked from another context and chalk does not show the colors then.

`kleur` shows them without any issues, is much smaller and faster.

**Comment by ghaiklor** [comment]
Thanks, I will investigate into differences between them.

**Comment by ghaiklor** [comment]
Done in https://github.com/ghaiklor/node-print-message/commit/eb303e5fcd08ed4a40c36d92c17e89d1d63f7957
